// <auto-generated />
using MVP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MVP.Data.Migrations
{
    [DbContext(typeof(MVPContext))]
    [Migration("20220101120603_AddSeed")]
    partial class AddSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MVP.Data.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Tax")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Austria",
                            Tax = 20.0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Belgium",
                            Tax = 21.0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bulgaria",
                            Tax = 20.0
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cyprus",
                            Tax = 19.0
                        },
                        new
                        {
                            Id = 5,
                            Name = "Czech Republic",
                            Tax = 21.0
                        },
                        new
                        {
                            Id = 6,
                            Name = "Croatia",
                            Tax = 25.0
                        },
                        new
                        {
                            Id = 7,
                            Name = "Denmark",
                            Tax = 25.0
                        },
                        new
                        {
                            Id = 8,
                            Name = "Estonia",
                            Tax = 20.0
                        },
                        new
                        {
                            Id = 9,
                            Name = "Finland",
                            Tax = 24.0
                        },
                        new
                        {
                            Id = 10,
                            Name = "France",
                            Tax = 20.0
                        },
                        new
                        {
                            Id = 11,
                            Name = "Germany",
                            Tax = 19.0
                        },
                        new
                        {
                            Id = 12,
                            Name = "Greece",
                            Tax = 24.0
                        },
                        new
                        {
                            Id = 13,
                            Name = "Hungary",
                            Tax = 27.0
                        },
                        new
                        {
                            Id = 14,
                            Name = "Ireland",
                            Tax = 23.0
                        },
                        new
                        {
                            Id = 15,
                            Name = "Italy",
                            Tax = 22.0
                        },
                        new
                        {
                            Id = 16,
                            Name = "Latvia",
                            Tax = 21.0
                        },
                        new
                        {
                            Id = 17,
                            Name = "Lithuania",
                            Tax = 21.0
                        },
                        new
                        {
                            Id = 18,
                            Name = "Luxembourg",
                            Tax = 17.0
                        },
                        new
                        {
                            Id = 19,
                            Name = "Malta",
                            Tax = 18.0
                        },
                        new
                        {
                            Id = 20,
                            Name = "Netherlands",
                            Tax = 21.0
                        },
                        new
                        {
                            Id = 21,
                            Name = "Poland",
                            Tax = 23.0
                        },
                        new
                        {
                            Id = 22,
                            Name = "Portugal",
                            Tax = 23.0
                        },
                        new
                        {
                            Id = 23,
                            Name = "Romania",
                            Tax = 19.0
                        },
                        new
                        {
                            Id = 24,
                            Name = "Slovakia",
                            Tax = 20.0
                        },
                        new
                        {
                            Id = 25,
                            Name = "Slovenia",
                            Tax = 22.0
                        },
                        new
                        {
                            Id = 26,
                            Name = "Spain",
                            Tax = 21.0
                        },
                        new
                        {
                            Id = 27,
                            Name = "Sweden",
                            Tax = 25.0
                        },
                        new
                        {
                            Id = 28,
                            Name = "United Kingdom",
                            Tax = 20.0
                        });
                });

            modelBuilder.Entity("MVP.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Apple",
                            Price = 100.0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Banana",
                            Price = 199.0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Car",
                            Price = 9990.5
                        },
                        new
                        {
                            Id = 4,
                            Name = "Pizza",
                            Price = 30.0
                        },
                        new
                        {
                            Id = 5,
                            Name = "Eggs",
                            Price = 24.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
